#+TITLE: SQL and PostgreSQL

In computing, a database is an organized collection of data. SQL is the software
that interacts with the database engine to capture and analyze data. Different
Database engines use different types of SQL, but most are similar enough to be
understandable if you know at least one.

In this repository I am going to skip over a lot of the basics of working with a
Database as I have already learned and relearned it a couple of times in my
life. There are plenty of guides online that can you teach you the basics quite
efficiently. I will however put snippets of sql files and general notes about
some of the topics I learn.

* Notes
** Keywords
   Postgres has the following keywords:
   - ~FROM~: Dictates which table to run query on.
   - ~SELECT~: Used to select rows from a table.
   - ~AS~: Used to dictate custom name for column in results.
** Column Data Types
   Postgres supports the following column data types:
   - ~VARCHAR(50)~: Variable length character. In this case our column would
     only accept strings less than or equal to 50 characters in length, but that
     number can be changed to any length we need.
   - ~INTEGER~: A number without a decimal within: =-2,147,483,647= to
     =2,147,483,647=. Anything larger or small will result in an error
** Math Operators
   Postgres supports the following math operators:
   - ~+~: Add
   - ~-~: Subtract
   - ~*~: Multiply
   - ~/~: Divide
   - ~^~: Exponent
   - ~|/~: Square Root
   - ~@~: Absolute Value
   - ~%~: Remainder
** String Operators and Functions
   Postgres supports the following string operator and functions:
   - ~||~: Join two strings
   - ~CONCAT()~: Join two strings
   - ~LOWER()~: Gives a lower case string
   - ~LENGTH()~: Gives number of characters in a string
   - ~UPPER()~: Gives an upper case string

** NoSQL vs. SQL
   When talking about SQL databases, we also have to mention the elephant in the
   room: ~NoSQL~.

   To put it simply, a NoSQL database is a database that does not use SQL
   (Structured Query Language). Each NoSQL typically has its own way of writing
   and executing queries. For example, MongoDB uses MQL (MongoDB Query Language)
   and ElasticSearch simply has a JSON API.

   While most relational databases are fairly similar, NoSQL databases tend to
   be fairly unique and are used for more niche purposes. Some of the main
   differences between a SQL and NoSQL databases are:

   NoSQL databases are usually non-relational, SQL databases are usually
   relational (we'll talk more about what this means later). SQL databases
   usually have a defined schema, NoSQL databases usually have dynamic
   schema. SQL databases are table-based, NoSQL databases have a variety of
   different storage methods, such as document, key-value, graph, wide-column,
   and more.

* SQL Engine specific notes
  Here are some notes on some specific sql engines:
  - [[./SQLite/README.org][SQLite]]: lightweight and self-contained relational database.
