#+TITLE: SQLite

SQLite is great for embedded projects, web browsers, and toy projects. It's
lightweight, but has limited functionality compared to the likes of PostgreSQL
or MySQL - two of the more common production SQL technologies.

One way in which SQLite is a bit different is that it stores Boolean values as
integers - the integers =0= and =1=.
- =0= = ~false~
- =1= = ~true~

Personally, SQLite and PostgreSQL are my favorites from the list above. Postgres
is a very powerful, open-source, production-ready SQL database. SQLite is a
lightweight, embeddable, open-source database. I usually choose one of these
technologies if I'm doing SQL work.

SQLite is a serverless database management system (DBMS) that has the ability to
run within applications, whereas PostgreSQL uses a Client-Server model and
requires a server to be installed and listening on a network, similar to an HTTP
server.

See a full comparison [[https://db-engines.com/en/system/PostgreSQL%3BSQLite][here]].

* Data Types
  Let's go over the data types supported by SQLite: and how they are stored.
  - ~NULL~ :: Null value.
  - ~INTEGER~ :: A signed integer stored in 0,1,2,3,4,6, or 8 bytes.
  - ~REAL~ :: Floating point value stored as a 64-bit IEEE floating point
    number.
  - ~TEXT~ :: Text string stored using database encoding such as UTF-8.
  - ~BLOB~ :: Short for Binary large object and typically used for images, audio
    or other multimedia.
  - ~BOOLEAN~ :: Boolean values are written in SQLite queries as true or false,
    but are recorded as 1 or 0.

** Boolean Values
   It's important to note - SQLite does not have a separate BOOLEAN storage
   class. Instead, boolean values are stored as integers:
   - =0= = ~false~
   - =1= = ~true~

* Constraint Limitation
  In other dialects of SQL you can ~ADD CONSTRAINT~ within an ~ALTER TABLE~
  statement. SQLite does not support this feature so when we create our tables
  we need to make sure we specify all the constraints we want! Here's a list of
  [[https://www.sqlite.org/omitted.html][SQL Features]] SQLite does not implement in case you're curious.

* ~AUTO INCREMENT~ in SQLite
  Different dialects of SQL will implement this feature differently, but in
  SQLite any column that has the ~INTEGER PRIMARY KEY~ constraint will auto
  increment! So we can omit the =id= field within the ~INSERT~ statement and
  allow the database to automatically add that field for us!

* SQL Functions
  SQL is a programming language and like nearly all programming languages, it
  supports functions. We can use functions and aliases to calculate new columns
  in a query. This is similar to how you might use formulas in Excel.

** The IIF Function
   In SQLite, the ~IIF~ function works like a ternary. For example:
   #+begin_src sql
     IIF(carA > carB, 'Car a is bigger', 'Car b is bigger')
   #+end_src

   If =carA= is greater than =carB=, this statement evaluates to the string
   ~'Car a is bigger'~. Otherwise, it evaluates to ~'Car b is bigger'~.

   Here's how we can use ~IIF()~ and a =directive= alias to add a new calculated
   column to our result set:
   #+begin_src sql
     SELECT quantity,
         IIF(quantity < 10, 'Order more', 'In Stock') AS directive
         FROM products;
   #+end_src

** ~BETWEEN~
   We can check if values are between two numbers using the ~WHERE~ clause in an
   intuitive way! The ~WHERE~ clause doesn't always have to be used to specify
   specific id's or values. We can also use it to help narrow down our result
   set. Here's an example:
   #+begin_src sql
     SELECT employee_name, salary
     FROM employees
     WHERE salary BETWEEN 30000 AND 60000;
   #+end_src

   This query returns all the employees =name= and =salary= fields for any rows
   where the =salary= is ~BETWEEN~ 30,000 and 60,000 inclusively! We can also
   query results that are ~NOT BETWEEN~ two specified values.
   #+begin_src sql
     SELECT product_name, quantity
     FROM products
     WHERE quantity NOT BETWEEN 20 AND 100;
   #+end_src

   This query returns all the product names where the quantity was not between
   =20= and =100=. We can use conditionals to make the results of our query as
   specific as we need them to be.

** Distinct
   Sometimes we want to retrieve records from a table without getting back any
   duplicates.

   For example, we may want to know all the different companies our employees
   have worked at previously, but we don't want to see the same company multiple
   times in the report.

   SQL offers us the ~DISTINCT~ keyword that removes duplicate records from the
   resulting query:
   #+begin_src sql
     SELECT DISTINCT previous_company
         FROM employees;
   #+end_src

   This only returns one row for each unique =previous_company= value.

** Logical Operators
   We often need to use multiple conditions to retrieve the exact information we
   want. We can begin to structure much more complex queries by using multiple
   conditions together to narrow down the search results of our query.

*** ~AND~ Operator
    #+begin_src sql
      SELECT product_name, quantity, shipment_status
      FROM products
      WHERE shipment_status = 'pending'
      AND quantity BETWEEN 0 and 10;
    #+end_src

    This only retrieves records where both the ~shipment_status~ is "pending"
    /AND/ the ~quantity~ is between =0= and =10=.

*** Comparison Operators
    All of the following operators are supported in SQL. The ~=~ is the main one
    to watch out for, it's not ~==~ like in many other languages! SQLite does
    allow for ~==~ but it's not a good habit to get into, as other dialects of
    SQL will not recognize ~==~ as valid syntax:
    - ~=~
    - ~<~
    - ~>~
    - ~<=~
    - ~>=~
    - ~<>~ or ~!=~

*** OR
    As you've probably guessed, if the logical ~AND~ operator is supported, the
    ~OR~ operator is probably supported as well:
    #+begin_src sql
      SELECT product_name, quantity, shipment_status
          FROM products
          WHERE shipment_status = 'out of stock'
          OR quantity BETWEEN 10 and 100;
    #+end_src

    This query retrieves records where either the =shipment_status= condition
    ~OR~ the quantity condition are met.

*** Order of Operations
    You can group logical operations with parentheses to specify the order of
    operations:
    #+begin_src sql
      (this AND that) OR the_other
    #+end_src

*** In
    Another variation to the ~WHERE~ clause we can utilize is the ~IN~
    operator. ~IN~ returns =true= or =false= if the first operand matches /any/
    of the values in the second operand. The ~IN~ operator is a shorthand for
    multiple ~OR~ conditions.

    These two queries are equivalent:
    #+begin_src sql
      SELECT product_name, shipment_status
          FROM products
          WHERE shipment_status IN ('shipped', 'preparing', 'out of stock');
    #+end_src

    #+begin_src sql
      SELECT product_name, shipment_status
          FROM products
          WHERE shipment_status = 'shipped'
              OR shipment_status = 'preparing'
              OR shipment_status = 'out of stock';
    #+end_src

    Hopefully, you're starting to see how querying specific data using
    fine-tuned SQL clauses helps reveal important insights! The larger a table
    becomes the harder it becomes to analyze without proper queries.

*** Like
    Sometimes we don't have the luxury of knowing /exactly/ what it is we need
    to query. Have you ever wanted to look up a song or a video but you only
    remember /part/ of the name? SQL provides us an option for when we're in
    situations ~LIKE~ this.

    The ~LIKE~ keyword allows for the use of the =%= and =_= wildcard
    operators. Let's focus on =%= first:

**** ~%~ Operator
     The =%= operator will match zero or more characters. We can use this
     operator within our query string to find more than just exact matches
     depending on where we place it:
     - Product Starts With “banana”:
       #+begin_src sql
         SELECT * FROM products
         WHERE product_name LIKE 'banana%';
       #+end_src
     - Product Ends With “banana”:
       #+begin_src sql
         SELECT * FROM products
         WHERE product_name LIKE '%banana';
       #+end_src
     - Product Contains “banana”:
       #+begin_src sql
         SELECT * FROM products
         WHERE product_name LIKE '%banana%';
       #+end_src

**** Underscore Operator
     As discussed, the =%= wildcard operator matches zero or more
     characters. Meanwhile, the =_= wildcard operator only matches a single
     character:
     #+begin_src sql
       SELECT * FROM products
           WHERE product_name LIKE '_oot';
     #+end_src

     The query above matches products like:
     - boot
     - root
     - foot

     #+begin_src sql
       SELECT * FROM products
           WHERE product_name LIKE '__oot';
     #+end_src

     The query above matches products like:
     - shoot
     - groot
